@ bot.command(name='єнот')
async def give_raccoon():
    phrases_one = ["тримай", "лови", "хапай", "на"]
    phrases_two = ["єнота", "єнотика"]
    await send(f"{USER}, {RAND(phrases_one)} {RAND(phrases_two)} {RAND(emotes_racc)}")


@ bot.command(name='пр')
async def say_hi_ua():
    await send(f"{USER}, {RAND(greetings_ua)} {RAND(emotes_greet + emotes_hand)}")


@ bot.command(name='hi')
async def say_hi_en():
    await send(f"{USER}, {RAND(greetings_en)} {RAND(emotes_greet + emotes_hand)}")


@ bot.command(name='фол', aliases=['fall', 'fg'])
async def fall_guys_instruction():
    code = content[4:]
    if code == "":
        code = "Lobby Code"
    await send(f"@{USER}, щоб доєднатись до нас в грі Fall Guys, виконайте наступні дії: Show Selector -> Custom Shows -> Join -> Enter {code}. Майте на увазі, цю гру можна безкоштовно завантажити в лаунчері Epic Games і важить вона приблизно 5ГБ")


@ bot.command(name='о', aliases=['so', 'шатаут'])
async def give_shoutout():
    await send(f"Підписуйтесь на файнюцького стрімера {USER}! {RAND(emotes_kiss)}")


@ bot.command(name='лиз')
async def lick_someone():
    phrases = ["Облизав", "Лизнув", "*Лизь*"]
    await send(f"{RAND(phrases)} {USER} {RAND(emotes_tongue)}")


@ bot.command(name='нюх')
async def smell_someone():
    phrases = ["Понюхав", "Обнюхав", "*Нюх-нюх*"]
    await send(f"{RAND(phrases)} {USER} {RAND(emotes_nose)}")


@ bot.command(name='мац')
async def touch_someone():
    phrases = ["Помацав", "Обмацав", "Полапав", "Облапав", "*Мацає*"]
    await send(f"{RAND(phrases)} {USER} {RAND(emotes_shy)}")


@ bot.command(name='пук')
async def fart_someone():
    phrases = ["Пукнув на", "Зіпсував повітря для", "*Пук* у бік"]
    await send(f"{RAND(phrases)} {USER} {RAND(emotes_laugh)}")


'''OUTDATED
@ bot.command(name='боб', aliases=['бобик'])
async def give_bob():
    chance = random.randint(-5, 30)
    phrases = ["ого", "йой", "чоловіче"]
    bob = ["бобика", "анаконду", "балумбу", "зміюку", "апарата",
           "шиликало", "списа", "кабачка", "банана", "патика", "шампура"]
    await send(f"{USER}, {RAND(phrases)}, маєш {RAND(bob)} у {chance} см! {RAND(emotes_laugh)}")
'''


@ bot.command(name='гам')
async def say_gam():
    shenanigans = ["гамно", "ГАМНО", "ГАМНООО", "ГАМНОО", "ГАМНОООО", "лайно", "ЛАЙНО",
                   "ЛАЙНОО", "ЛАЙНООО", "ЛАЙНОООО", "гівно", "ГІВНО", "ГІВНОО", "ГІВНООО", "ГІВНОООО"]
    await send(f"{USER}, лови {RAND(shenanigans)} {RAND(emotes_poo + emotes_shy)}")


@ bot.command(name='бан')
async def ban_user():
    one = ["Вітаю з баном", "Вас було забанено", "Ви були забанені", "Вам бан"]
    two = ["", "на цьому каналі", "на каналі PixelFedya",
           "на поточному каналі", "на файному каналі"]
    global goodbye_ua
    await send(f"{USER}, {RAND(one)} {RAND(two)}! {RAND(goodbye_ua)} {RAND(emotes_laugh)}")


@ bot.command(name='бам')
async def play_roulette():
    username = '@' + USER
    current_chamber = random.randint(1, 3)
    bullet_chamber = random.randint(1, 3)
    phrase = ["сьогодні", "на цей раз", "цього разу", ""]
    one = ["Вітаю з баном", "Вас було забанено", "Ви були забанені", "Вам бан"]
    two = ["", "на цьому каналі", "на каналі PixelFedya",
           "на поточному каналі", "на файному каналі"]
    roll = ["Розкручую", "Кручу", "Прокручую"]
    if current_chamber == bullet_chamber:
        await send(f"{RAND(roll)} барабан... {RAND(emotes_pistol)} {USER}, {RAND(one)} {RAND(two)}! {RAND(goodbye_ua)} {RAND(emotes_laugh)}")
    else:
        await send(f"{RAND(roll)} барабан... {RAND(emotes_pistol)} {USER}, {RAND(phrase)} Вам пощастило! Револьвер не вистрілив {RAND(emotes_shy)}")


@ bot.command(name='цьом')
async def say_gam():
    phrases = ["Цьомнув", "Поцьомав",
               "*Надсилає цьомчика*", "*Цьомає*", "Цьом"]
    await send(f"{RAND(phrases)} {USER} {RAND(emotes_kiss)}")


@ bot.command(name='додай')
async def add_feature():
    await send(f"@seesmof, {content[6:]}, бігом додавати!")


@ bot.command(name='тг')
async def telegram_show():
    await send(f"@{USER}, аби не пропускати стріми Піксельного, підписуйтесь на наш Телеграм канал за посиланням @pixelfedya в пошуку Телеграму TehePelo")


@ bot.command(name='гпт')
async def gpt_instruction_ua():
    await send(f"@{USER}, для того, щоб отримати відповідь від ChatGPT, просто почніть Ваше повідомлення з @wuyodo і продовжіть Вашим питанням. Через деякий час ви отримаєте відповідь, згенеровану ботом ChatGPT :)")


@ bot.command(name='gpt')
async def gpt_instruction_en():
    await send(f"@{USER}, to get a response from ChatGPT, just start your message with @wuyodo and continue with your question. After a while, you will receive an answer generated by the ChatGPT bot :)")


@ bot.command(name='окса')
async def hi_oxa():
    await send(f"Оксано, привіт!")


@ bot.command(name='щіщ', aliases=['шіш', 'щіш', 'шіщ'])
async def say_sheesh_ua():
    shenanigans = ["щіщ", "ЩІЩ", "ЩІІЩ", "ЩІІІЩ", "ЩІІІІЩ"]
    await send(f"@{USER}, {RAND(shenanigans)}")


@ bot.command(name='зріст')
async def give_height():
    await send(f"@{USER}, зріст стрімера приблизно становить 182 см")


@ bot.command(name='she')
async def say_sheesh_en():
    shenanigans = ["sheesh", "SHEESH", "SHEEESH", "SHEEEESH", "SHEEEEESH"]
    await send(f"@{USER}, {RAND(shenanigans)}")


@ bot.command(name='дн')
async def birthday_congrats():
    greetings = ['З днем народження! Сьогодні день, коли здійснюються Ваші мрії і виконуються Ваші бажання. У цей особливий день я бажаю Вам щастя та успіху на все життя. Нехай благополуччя, радість і любов оточують Вас сьогодні і завжди. Всього найкращого в цей особливий день!', 'З Днем народження! Це Ваш особливий день, і я бажаю Вам щасливого святкування! Нехай цей день буде наповнений радістю, міцним здоров`ям і великою удачею. Нехай наступний рік буде сповнений успіхом та щастям. Насолоджуйтесь особливими моментами свого дня народження та цінуйте любов і тепло своїх близьких. Нехай наступний рік буде найкращим!',
                 'З Днем народження! Нехай цей особливий день буде наповнений радістю і сміхом. Нехай Ваше серце буде переповнене щастям, а дні будуть сповнені чудовими моментами. Бажаємо удачі та успіхів у всіх Ваших починаннях. Фантастичного дня!!', 'З Днем народження! Нехай цей особливий день буде наповнений радістю та світлими почуттями. Бажаємо Вам всього найкращого в житті, нехай здійсняться всі Ваші мрії та прагнення. Нехай наступний рік буде надзвичайно успішним!', 'Вітаємо з днем народження у цей особливий день! Нехай цей рік принесе Вам багато позитиву, радості та успіху. Бажаю Вам всього найкращого в житті, і нехай всі Ваші мрії здійсняться. Гарного дня та чудового наступного року!', 'Вітаємо з днем народження! Нехай цей особливий день буде наповнений морем веселощів, любові та сміху. Бажаю, щоб цей рік був чудовим і щоб Ви досягли всіх своїх цілей. Бажаю прекрасного життя, сповненого благословень. З днем народження!']
    await send(f"{USER}, {RAND(greetings)}")


@ bot.command(name='шанс')
async def give_chance():
    chance = random.randint(1, 100)
    await send(f"@{USER}, вірогідність цього становить {chance}%.")


@ bot.command(name='ем', aliases=['емоджі', 'емоція', 'emoji', 'em'])
async def print_random_emoji():
    global_emotes_list = emotes_all_twitch
    await send(RAND(global_emotes_list))


@ bot.command(name='пк', aliases=['сетап', 'комп'])
async def show_pc_specs():
    await send(f"@{USER}, процесор - Intel Core i7-13700K, відеокарта - NVidia Geforce RTX 3080, камера - Logitech BRIO 4K, пам'ять - Corsair Vengance 32 ГБ 5600MHz, навушники - SteelSeries Arctis Nova 7, мікрофон - HyperX Quadcast S, клавіатура - MSI Interceptor DS4100, миша - SteelSeries Rival 110, монітори - MSI 32' 144Hz та AOC 24' 144Hz")


@ bot.command(name='мак', aliases=['слимак', 'слимачок'])
async def act_slug():
    phrases = ["Можливо, я повільний, але я завжди у русі. Ніколи не знаєш, де я можу опинитися наступного разу!",
               "Я справжній поштовий равлик. Тільки не сподівайтеся, що я доставлю щось вчасно",
               "Нехай у мене немає мушлі, але мені все одно заздрять усі равлики",
               "Я нікуди не поспішаю, я просто насолоджуюся подорожжю. Навіть якщо це займе у мене цілий день",
               "Може, я й маленький, але я дуже люблю залишати сліди",
               "Я не лінивий, я просто зберігаю свою енергію на той час, коли вона мені дійсно потрібна",
               "Я не заблукав, я просто йду мальовничим маршрутом",
               "Можливо, я не найшвидший, але я точно найспритніший",
               "Я не слизький, я просто випромінюю свою природну чарівність,"
               "Я не слимак, я слимак-зайчик!"
               "Я не равлик, я переодягнений слимак. Тсс, нікому не кажи",
               "Можливо, у мене немає хребта, але я можу постояти за себе",
               "Я не повільний, я просто насолоджуюся моментом",
               "Я не слимак, я слимацька суперзірка!",
               "Мій панцир не просто для показухи, це мій пересувний дім",
               "Я не просто равлик, я ніндзя уповільненої дії",
               "Я не люблю дощ, це все одно, що приймати душ в одязі",
               "Я равлик, а не черепаха. Зрозумійте це правильно, люди!",
               "Я не лінивий, я просто економлю енергію",
               "Я не шкідник саду, я його прикрашаю",
               "Я не просто равлик, я швидкісний гонщик в сповільненій зйомці",
               "Я не боюся птахів, вони мене просто підвозять",
               "Я не закуска, я делікатес",
               "Я не слизький, я просто трохи вологий",
               "Я не повільний, я просто не поспішаю",
               "Я не слимак, я равлик зі стилем",
               "Я не повільний, я просто насолоджуюся життям",
               "Може, я і слизький, але принаймні не липкий",
               "Я, можливо, маленький, але у мене велика особистість",
               "Я не боюся птахів, це птахи бояться мене",
               "Я не шкідник, я гість",
               "Я не слизький, я спритний",
               "Я не просто слимак, я замаскований супергерой",
               "Я як равлик, але без будиночка",
               "Я не нудний, мене просто не розуміють",
               "Можливо, я повільний, але в кінці кінців я завжди досягаю мети",
               "Тихіше їдеш - далі будеш, друже!"
               "Не дозволяй нікому казати тобі, що ти не можеш чогось досягти, навіть якщо це займе певний час",
               "Ти можеш бути маленьким, але по-своєму сильним!",
               "Продовжуй рухатися вперед, навіть якщо це лише потроху за раз",
               "Кожна подорож починається з одного кроку, або, як у моєму випадку, з одного слизького сліду",
               "Вір у себе, навіть коли інші не вірять",
               "Не поспішай, і ти все одно досягнеш мети",
               "Шлях до успіху може бути довгим, але врешті-решт він того вартий",
               "Ніколи не здавайся, навіть коли стає важко",
               "Життя сповнене перешкод, але у тебе є сили, щоб їх подолати",
               "Ти не повільний, ти просто насолоджуєшся подорожжю",
               "Не порівнюй себе з іншими, ти по-своєму унікальний",
               "Найголовніше - це продовжувати рухатися вперед, незалежно від того, наскільки малим є прогрес",
               "Пам'ятай, що кожна невдача - це лише підготовка до майбутнього успіху",
               "Ти не просто слимак, ти першопроходець!",
               "Не дозволяй нікому притупити твою іскру, продовжуй сяяти!",
               "Подорож може бути довгою, але вид з вершини того вартий",
               "У тебе всередині є сила, щоб досягти всього, що ти захочеш",
               "Навіть равлики колись були слимаками, тому продовжуй рухатися вперед і ти досягнеш мети"
               ]
    await send(f"@{USER}, {RAND(phrases)} {RAND(emotes_slug)}")


@ bot.command(name='чого')
async def who_is_he():
    await send(f"@{USER}, стрімера звати Василь, але він має прізвище Фединяк, тому друзі називають його Федя. Ви можете називати його як вам завгодно :)")


@ bot.command(name='де')
async def where_from():
    await send(f"@{USER}, стрімер родом з Івано-Франківської області, але наразі перебуває в Англії :)")


@ bot.command(name='блін')
async def no_ignore_please():
    await send(f"@PixelFedya")
    await asyncio.sleep(2)
    input_txt = content[5:]
    await send_split_gpt(input_txt)
    await asyncio.sleep(2)
    await send(f"@PixelFedya")


@ bot.command(name='батько', aliases=['бат', 'батя'])
async def who_father():
    phrase = ["мабуть є", "то є", "скоріш за все є",
              "походу є", "то, нажаль, є"]
    await send(f"@{USER}, твій батько {RAND(phrase)} {USER} {RAND(emotes_all_twitch)}")


@ bot.command(name='шлик', aliases=['члик', 'сюди'])
async def invoke_duel():
    phrase = ["шиликнув", "пошиликав", "чиликнув", "почиликав"]
    phrase_two = ["яйоли", "яєчки", "яйки", "balls", "cock", "бобика", "анаконду", "балумбу", "зміюку", "апарата",
                  "шиликало", "списа", "кабачка", "банана", "патика", "шампура"]
    await send(f"@{USER}, {RAND(phrase)} за {RAND(phrase_two)} {USER}  {RAND(emotes_all_twitch)}")


@ bot.command(name='коц', aliases=['буц', 'яйк'])
async def easter_fight():
    users = [USER, username]
    result = RAND(users)
    await send(f"@{USER}, цокнувся яйолами з {USER}. {result} переміг!")


@ bot.command(name='дуп', aliases=['поп', 'ass'])
async def easter_fight():
    phrases = ["показав", "помацав", "полапав", "пощупав"]
    wut = ["дупу", "сраку", "волохату дупу"]
    await send(f"@{USER} {RAND(phrases)} {RAND(wut)} {USER} {RAND(emotes_all_twitch)}")


@ bot.command(name='ня')
async def easter_fight():
    await send(f"@{USER} MercyWing1 {RAND(emotes_all_twitch)} MercyWing2")


@ bot.command(name='уа')
async def easter_fight():
    await send(f"@{USER} PowerUpL {RAND(emotes_all_twitch)} PowerUpR")


@ bot.command(name='дс', aliases=['ds', 'discord'])
async def discord_show():
    await send(f"@{USER}, доєднуйтесь до нас в Discord - *discord.gg/KX6e8K96Cd* TehePelo")
